name: Lint Pull Request
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  lint-pr:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: "[Lint] Check pull request title"
        uses: jef/conventional-commits-pr-action@v1
        with:
          comment: true
          token: ${{ secrets.GITHUB_TOKEN }}
